#!/bin/sh
set -euxo pipefail

FILE=/usr/bin/java.corretto-11-bin
if [ -f "$FILE" ]; then
    echo "$FILE exists. Using alternate java name to test."
    $FILE --version
else
    echo "$FILE does not exist. Using default java to test."
    java --version
fi

RETVAL=$?
if [ $RETVAL -eq 0 ] ; then
    echo "PASS: corretto-11-bin startup test"
else
    echo "FAIL: corretto-11-bin startup test"
fi

cd /greengrass/v2/alts/current/distro/bin
chmod 755 loader
./loader  2>&1 > test.log &
sleep 30
grep "Launched Nucleus successfully" test.log

RETVAL=$?
if [ $RETVAL -eq 0 ] ; then
    echo "PASS: corretto-11-bin -> greengrass-bin startup test"
else
    echo "FAIL: corretto-11-bin -> greengrass-bin startup test"
fi