#!/bin/sh
# Copyright (c) 2022 Amazon.com, Inc. or its affiliates.
# SPDX-License-Identifier: MIT

find tests -executable -type f -exec bash -c '{} --gtest_output=json:result.json > /dev/null ;  python3 ptest_result.py result.json ' \;