#!/bin/sh

echo nameserver 8.8.4.4 >> /etc/resolv.conf 

cd tests/

# known good tests
TESTS="\
test/test_ggv2.py \
test/test_mqtt.py \
test/test_mqtt5.py \
test/test_rpc.py \
test/test_samples.py \
test/test_shadow_state.py \
"

for TEST in $TESTS
do
    python3 -m unittest $TEST
    RETVAL=$?
    if [ $RETVAL -eq 0 ] ; then
        echo "PASS: aws-crt-python unittest: $TEST"
    else
        echo "FAIL: aws-crt-python unittest: $TEST"
    fi
done

### removed tests####
#
