#!/bin/sh

cd tests

rm -rf tests.log

# known good tests
TESTS="\
test_crc32c \
test_crc32 \
"

for TEST in $TESTS
do
./aws-checksums-tests $TEST >> tests.log
done

sed  -e '/OK/ s/^/PASS: / ; /FAILED/ s/^/FAIL: / ; /ERROR/ s/^/FAIL: /' tests.log
