SUMMARY = "AWS libcrypto (AWS-LC)"
DESCRIPTION = "AWS-LC is a general-purpose cryptographic library maintained by the AWS Cryptography team for AWS and their customers. It іs based on code from the Google BoringSSL project and the OpenSSL project."

HOMEPAGE = "https://github.com/awslabs/aws-lc"

LICENSE = "Apache-2.0"
LIC_FILES_CHKSUM = "file://LICENSE;md5=2c554710bb1c4067a60ae89090fcbc06"

PROVIDES += "aws/lc"

BRANCH ?= "main"

SRC_URI = "git://github.com/awslabs/aws-lc.git;protocol=https;branch=${BRANCH} \
           file://run-ptest \
           file://0001-Make-all-directory-names-lowercase.patch \
           file://0002-Add-optimized-2048-bit-squaring.patch \
           file://0003-Add-256-bit-and-384-bit-big-endian-conversions.patch \
           file://0004-Add-256-bit-and-384-bit-specializations-of-multiplex.patch \
           file://0005-Add-256-bit-and-384-bit-specializations-of-nonzerone.patch \
           file://0006-Remove-separate-almost-Montgomery-functions-for-P-25.patch \
           file://0007-Add-first-P-521-function-modular-addition.patch \
           file://0008-Add-P-521-modular-subtraction.patch \
           file://0009-Add-P-521-modular-doubling.patch \
           file://0010-Add-P-521-modular-halving.patch \
           file://0011-Standardize-numeric-literals-in-ARM-code-to-use-symb.patch \
           file://0012-Add-P-521-modular-tripling.patch \
           file://0013-Regularize-.text-and-other-directives.patch \
           file://0014-Add-non-executable-stack-directives-to-all-asm-files.patch \
           file://0015-Switch-P-256-and-P-384-code-from-assembler-macros-to.patch \
           file://0016-Add-P-521-native-size-modulus.patch \
           file://0017-Add-P-521-multiplication-by-single-word.patch \
           file://0018-Add-optimized-2048-bit-multiplication.patch \
           file://0019-Consistently-use-upper-case-for-constants.patch \
           file://0020-Add-P-521-modular-squaring.patch \
           file://0021-Add-P-521-Montgomery-squaring.patch \
           file://0022-Add-P-521-mapping-from-Montgomery.patch \
           file://0023-Add-P-521-mapping-from-almost-Montgomery.patch \
           file://0024-Remove-constant-expressions-and-make-other-small-twe.patch \
           file://0025-Add-P-521-modular-negation.patch \
           file://0026-Add-P-521-optional-modular-negation.patch \
           file://0027-Add-AT-T-syntax-versions-of-x86-P-384-functions.patch \
           file://0028-Add-AT-T-syntax-versions-of-x86-P-256-functions.patch \
           file://0029-Add-AT-T-syntax-versions-of-x86-P-521-functions.patch \
           file://0030-Add-explicit-alignment-to-ARM-text-sections.patch \
           file://0031-Remove-spaces-in-function-like-macro-invocations.patch \
           file://0032-Replace-a-few-ARM-extract-instructions-with-simple-s.patch \
           file://0033-Add-P-521-modular-multiplication.patch \
           file://0034-Add-P-521-Montgomery-multiplication.patch \
           file://0035-Add-P-521-native-size-group-order-modulus.patch \
           file://0036-Slightly-improve-ARM-bignum_mod_p521_9.patch \
           file://0037-Add-conversion-into-Montgomery-form-for-P-521.patch \
           file://0038-Eliminate-a-few-more-constant-expressions.patch \
           file://0039-Add-little-endian-conversions-for-P-256-and-P-384.patch \
           file://0040-Add-generic-squaring-function.patch \
           file://0041-Fix-typos-in-comments-regenerate-nonbmi_functions-li.patch \
           file://0042-Add-alternative-variants-of-P-384-Montgomery-operati.patch \
           file://0043-Add-non-BMI-forms-of-remaining-x86-P-384-functions.patch \
           file://0044-Add-alternative-variants-of-P-521-modular-and-Montgo.patch \
           file://0045-Add-non-BMI-forms-of-remaining-x86-P-521-functions.patch \
           file://0046-Add-P-521-little-endian-byte-serialization-and-deser.patch \
           file://0047-Add-mangled-names-for-globals-to-each-function-for-M.patch \
           file://0048-Liberalize-input-output-aliasing-conditions-on-P-521.patch \
           file://0049-Regularize-spacing-of-assembler-files.patch \
           file://0050-Add-Windows-ABI-wrappers.patch \
           file://0051-Platform-aware-symbol-macros.patch \
           file://0052-Cleanup-and-indentation.patch \
           file://0053-include-_internal_s2n_bignum.h.patch \
           file://0054-Invoke-cpp-as-E.patch \
           file://0055-Use-.hidden-directive-on-non-Apple-platforms.patch \
           file://0056-Use-CC-E-for-preprocessor.patch \
           file://0057-Several-files-missing-.text-directive.patch \
           file://0058-Re-make-x86_att.patch \
           file://0059-Add-basic-NIST-P-384-point-operations.patch \
           file://0060-Add-basic-NIST-P-384-point-operations.patch \
           file://0061-Tweak-ARM-bignum_sqr_p521_alt-to-use-fewer-registers.patch \
           file://0062-Tweak-ARM-bignum_sqr_p521_alt-to-use-fewer-registers.patch \
           file://0063-Add-basic-NIST-P-521-point-operations.patch \
           file://0064-Add-basic-NIST-P-521-point-operations.patch \
           file://0065-Add-X25519-function.patch \
           file://0066-Add-X25519-function.patch \
           file://0067-Add-curve25519-field-doubling.patch \
           file://0068-Add-curve25519-field-doubling.patch \
           file://0069-Update-forgotten-AT-T-syntax-forms-in-line-with-prev.patch \
           file://0070-Update-forgotten-AT-T-syntax-forms-in-line-with-prev.patch \
           file://0071-update-license-headers-of-.c-and-.s-files.patch \
           file://0072-update-license-headers-of-.c-and-.s-files.patch \
           file://0073-update-license-headers-of-.c-and-.s-files.patch \
           file://0074-update-license-headers-of-Makefiles-and-sed-files.patch \
           file://0075-update-license-headers-of-Makefiles-and-sed-files.patch \
           file://0076-update-license-headers-of-Makefiles-and-sed-files.patch \
           file://0077-Add-X25519-basepoint-function.patch \
           file://0078-Add-X25519-basepoint-function.patch \
           file://0079-Add-SM2-mapping-to-Montgomery-representation.patch \
           file://0080-Add-SM2-mapping-to-Montgomery-representation.patch \
           file://0081-Add-SM2-mapping-to-Montgomery-representation.patch \
           file://0082-Add-SM2-field-negation.patch \
           file://0083-Add-SM2-field-negation.patch \
           file://0084-Add-SM2-field-negation.patch \
           file://0085-Add-SM2-field-doubling-and-halving.patch \
           file://0086-Add-SM2-field-doubling-and-halving.patch \
           file://0087-Add-SM2-field-doubling-and-halving.patch \
           file://0088-Emphasize-that-bindings-are-autogenerated-778.patch \
           file://0089-Add-Rust-Docker-Images-README.md-for-AL2-Linux-780.patch \
           file://0090-Add-CI-that-uses-M1-Mac-ec2-Instance-773.patch \
           file://0091-Small-fix-for-M1-ec2-CI-script-782.patch \
           file://0092-API-diff-during-Rust-crate-generation-781.patch \
           file://0093-Move-x86-valgrind-to-AL2022-fix-known-valgrind-supre.patch \
           file://0094-Turn-on-static-FIPS-build-for-Android-752.patch \
           file://0095-Improve-X.509-GeneralName-parsing.-789.patch \
           file://0096-Bump-release-version-to-v1.4.0-792.patch \
           file://0097-Update-Rust-crate-bindgen-794.patch \
           file://0098-Use-CAVP-test-data-for-SSHKDF-KATs-777.patch \
           file://0099-update-ssm-document-to-handle-s3-files-787.patch \
           file://0100-Fix-build-on-openbsd-764.patch \
           file://0101-Drop-the-preference-for-256-bit-ciphers-with-CECPQ2.patch \
           file://0102-Remove-hmac.h-include-from-ssl.h.patch \
           file://0103-Add-over_message-issuance-and-redemption-to-Trust-To.patch \
           file://0104-Add-sk_FOO_delete_if.patch \
           file://0105-Empty-stacks-are-vacuously-sorted.patch \
           file://0106-Further-const-correct-config-based-extension-creatio.patch \
           file://0107-Remove-the-last-of-the-filename-comments.patch \
           file://0108-Deprecate-test-and-document-X.509-config-APIs.patch \
           file://0109-Const-correct-sk_FOO_deep_copy-s-copy-callback.patch \
           file://0110-Remove-no-op-entries-from-asn1_str2tag.patch \
           file://0111-Test-that-policy-checking-always-succeeds-with-just-.patch \
           file://0112-Add-optimised-Aarch64-GCM.patch \
           file://0113-Update-build-files-in-generated-src.patch \
           file://0114-Stop-clang-from-un-constant-timing-copy_from_prebuf.patch \
           file://0115-Avoid-branches-in-GCC-in-bn-generic.c.patch \
           file://0116-Slightly-optimize-x86-modular-inverse-inner-loop.patch \
           file://0117-Slightly-optimize-x86-modular-inverse-inner-loop.patch \
           file://0118-Different-symbols-prefix-for-FIPS-798.patch \
           file://0119-Adding-Kyber768-and-Kyber1024-round-3-KEMs-784.patch \
           file://0120-migrate-over-to-aws-organization-809.patch \
           file://0121-Allow-override-of-git-clone-URL-and-branch-to-allow-.patch \
           file://0122-Fix-crash-if-section-is-used-with-no-CONF.patch \
           file://0123-Handle-errors-more-normally-in-asn1_gen.c.patch \
           file://0124-Rename-CTX_TEST-to-X509V3_CTX_TEST.patch \
           file://0125-Reduce-caller-requirements-on-X509V3_CTX.patch \
           file://0126-Indent-DB-lines-in-x86_64-NASM-output.patch \
           file://0127-Rewrite-X.509-policy-tree-logic.patch \
           file://0128-Add-initial-support-for-SEH-directives-in-x86_64-per.patch \
           file://0129-Convert-ghash-x86_64.pl-to-new-directives.patch \
           file://0130-Don-t-automatically-sync-the-two-CONF-parameters-in-.patch \
           file://0131-Maintain-a-frame-pointer-in-aesni-gcm-x86_64.pl-and-.patch \
           file://0132-Fix-inhibitPolicyMapping-in-the-new-policy-tree-code.patch \
           file://0133-Add-bash-script-to-install-common-depednecies-update.patch \
           file://0134-Add-FIPS-CI-for-all-linux-dimensions-783.patch \
           file://0135-Allow-keys-without-e-in-RSA_set0_key-814.patch \
           file://0136-Measure-entire-X25519-work-for-easy-comparison-with-.patch \
           file://0137-Migrate-io-ioutil-uses-to-new-APIs.-816.patch \
           file://0138-Move-all-fuzzing-to-al2022-with-clang-14-815.patch \
           file://0139-Use-PROJECT_SOURCE_DIR-and-PROJECT_BINARY_DIR-in-CMa.patch \
           file://0140-Unexport-BN_MONT_CTX_set_locked.patch \
           file://0141-Add-a-WORKSPACE.toplevel-file.patch \
           file://0142-Don-t-send-two-post-quantum-initial-key-shares.patch \
           file://0143-Work-around-nasm-bug-with-empty-assembly-files.patch \
           file://0144-Use-the-same-Deleter-across-all-bssl-UniquePtr-T.patch \
           file://0145-Update-build-files-in-generated-src.patch \
           file://0146-Fix-BORINGSSL_PREFIX_HEADERS_PATH-not-included-in-cp.patch \
           file://0147-Merge-PKCS-8-V2-RFC-5958-Support-into-main-828.patch \
           file://0148-Fix-RelWithDebInfo-with-FIPS-build-on-Windows-819.patch \
           file://0149-Revert-Kyber-verify-841.patch \
           file://0150-Test-HKDF_expand-as-a-FIPS-KDF-via-CAVP-data-840.patch \
           file://0151-Allow-RSA-keys-with-d-n-to-be-imported-844.patch \
           file://0152-Loosen-modular-reductions-in-X25519-basepoint-functi.patch \
           file://0153-Loosen-modular-reductions-in-X25519-basepoint-functi.patch \
           file://0154-Release-v1.5.0-843.patch \
           file://0155-Add-Stale-Issue-GitHub-Workflow-842.patch \
           file://0156-Fix-typo-in-stale_issue.yml-852.patch \
           file://0157-Align-ppc-assembly-setup-with-other-architectures.patch \
           file://0158-Add-CBS_get_u64_decimal.patch \
           file://0159-Switch-ERR_GET_-to-inline-functions.patch \
           file://0160-Remove-old-Trust-Token-redeem-API.patch \
           file://0161-Add-tests-for-X509_NAME_hash-and-X509_NAME_hash_old.patch \
           file://0162-Introduce-a-locale-independent-version-of-isspace.patch \
           file://0163-Introduce-constants-for-ASN1_BOOLEAN.patch \
           file://0164-Add-some-tests-for-optional-and-default-ASN1_BOOLEAN.patch \
           file://0165-Rewrite-ASN1_generate_v3.patch \
           file://0166-Add-a-fuzzer-for-the-config-file-machinery.patch \
           file://0167-Introduce-a-locale-independent-version-of-isdigit.patch \
           file://0168-Remove-now-unnecessary-check-in-CBS_peek_asn1_tag.patch \
           file://0169-Fix-error-handling-in-X509V3_EXT_add_nconf_sk-and-X5.patch \
           file://0170-Check-for-null-value-in-set_dist_point_name.patch \
           file://0171-Mark-standalone-Go-scripts-with-go-build-ignore.patch \
           file://0172-Fix-stray-s-in-line-comment-license-headers.patch \
           file://0173-Simplify-a-pair-of-Go-range-expressions.patch \
           file://0174-Loosen-modular-reductions-in-X25519-fresh-point-func.patch \
           file://0175-Loosen-modular-reductions-in-X25519-fresh-point-func.patch \
           file://0176-Remove-old-Rust-bindings-that-have-been-relocated-85.patch \
           file://0177-Reorder-some-field-operations-in-X25519-functions.patch \
           file://0178-Reorder-some-field-operations-in-X25519-functions.patch \
           file://0179-Eliminate-5-digit-intermediates-in-ARM-X25519-functi.patch \
           file://0180-Eliminate-5-digit-intermediates-in-ARM-X25519-functi.patch \
           file://0181-KEM-fix-key-retrieval-when-public-secret-key-is-miss.patch \
           file://0182-Propagate-field-operation-improvements-to-ARM-X25519.patch \
           file://0183-Propagate-field-operation-improvements-to-ARM-X25519.patch \
           file://0184-Add-AES-CCM-ECB-CTR-KW-to-test_fips-tool-853.patch \
           file://0185-AWS-LC-does-not-provide-Time-Stamp-Authority-functio.patch \
           file://0186-fix-dockerfile-and-add-CI-support-for-CentOS-860.patch \
           file://0187-Get-rid-of-time_t-usage-internally-change-to-int64_t.patch \
           file://0188-Rename-bssl-to-awslc-add-version-cmd-865.patch \
           file://0189-AWS-LC-does-not-support-the-OpenSSL-memory-debug-API.patch \
           file://0190-Avoid-potential-for-buffer-overflow-in-SHA3-ARMv8-as.patch \
           file://0191-Fix-leak-on-invalid-input-to-a2i_GENERAL_NAME.patch \
           file://0192-Make-X509V3_get_value_int-free-the-old-value-before-.patch \
           file://0193-Remove-the-last-of-the-broken-NEON-workaround.patch \
           file://0194-Correctly-handle-optional-ASN1_ITEM_TEMPLATE-types.patch \
           file://0195-Add-locale-independent-implementations-of-isalpha-is.patch \
           file://0196-Align-header-guard-style-in-the-remaining-headers.patch \
           file://0197-Cap-bit-indices-in-the-unsafe-string-based-X.509-ext.patch \
           file://0198-Fix-leak-on-error-in-v2i_POLICY_MAPPINGS.patch \
           file://0199-Fix-some-clang-format-formatting.patch \
           file://0200-Fix-leak-in-error-handling-for-issuingDistributionPo.patch \
           file://0201-Bump-release-version-to-v1.5.1-871.patch \
           file://0202-Update-the-CI-docker-images-documentation-876.patch \
           file://0203-Use-function-reference-to-get-cpu-capability-vector-.patch \
           file://0204-Update-analytics-script-to-handle-new-tool-name-from.patch \
           file://0205-add-bss-segment-and-separate-const-segment-from-data.patch \
           file://0206-Add-basic-SM2-point-operations.patch \
           file://0207-Add-basic-SM2-point-operations.patch \
           file://0208-Add-basic-SM2-point-operations.patch \
           file://0209-Add-checks-to-ensure-that-OPENSSL_ia32cap-is-not-in-.patch \
           file://0210-update-readme-to-address-changes-to-the-windows-FIPS.patch \
           file://0211-Remove-docker-images-used-for-Rust-crate-gen-888.patch \
           file://0212-Stringify-enum-to-pretty-print-errors-890.patch \
           file://0213-clang-format-a-subset-of-files-892.patch \
           file://0214-Fix-minor-documentation-formating-issues-and-build-t.patch \
           file://0215-Add-byte-level-interfaces-for-X25519-functions.patch \
           file://0216-Add-byte-level-interfaces-for-X25519-functions.patch \
           file://0217-Add-byte-level-interfaces-for-X25519-functions.patch \
           file://0218-revert-back-to-using-bssl-as-tool-name-895.patch \
           file://0219-Fix-leak-in-set_dist_point_name-error-handling.patch \
           file://0220-Const-correct-the-various-EVP_PKEY-PEM-writers.patch \
           file://0221-Reject-even-moduli-in-RSA_check_key.patch \
           file://0222-Rearrange-bn-generic.c.patch \
           file://0223-Add-bn_add_words-and-bn_sub_words-assembly-for-aarch.patch \
           file://0224-Fix-various-malloc-failure-paths.patch \
           file://0225-Limit-the-CMake-isysroot-assembly-workaround-to-olde.patch \
           file://0226-Remove-old-clang-cl-workaround.patch \
           file://0227-Also-test-i2d_GENERAL_NAME-in-X509Test.GeneralName.patch \
           file://0228-Unexport-GENERAL_NAME_cmp.patch \
           file://0229-Remove-if-d-out-OCB-AES-assembly.patch \
           file://0230-Remove-stale-TODO-in-util-bot-DEPS.patch \
           file://0231-Update-build-files-in-generated-src.patch \
           file://0232-Added-RSA-3072-sign-verify-to-the-speed-tool-877.patch \
           file://0233-Add-missing-APIs-to-better-support-Bind-904.patch \
           file://0234-Disable-3DES-by-default-906.patch \
           file://0235-Bump-release-version-to-v1.6.0-909.patch \
           file://0236-Enable-Valgrind-testing-for-libssl-912.patch \
           file://0237-Add-SHA3_Squeeze-output-buffer-overflow-test-893.patch \
           file://0238-Enable-SHA3-deprecate-its-opt-in-functions-898.patch \
           file://0239-Zeroize-data-immediately-after-use-for-FIPS-911.patch \
           file://0240-Merge-branch-s2n-bignum-2023-03-31-into-aws-lc-s2n-b.patch \
           file://0241-Remove-remaining-branches-in-bn-generic.c-919.patch \
           file://0242-Build-flag-AWS_LC_IGNORE_BN_SET_FLAGS-918.patch \
           file://0243-Revert-Merge-branch-s2n-bignum-2023-03-31-into-aws-l.patch \
           file://0244-Clean-up-test_support_lib-and-GTest-dependencies-sli.patch \
           file://0245-Remove-global_target-from-build.patch \
           file://0246-Make-boringssl_gtest_main-a-STATIC-library.patch \
           file://0247-Specify-Iinclude-with-the-crypto-target.patch \
           file://0248-Reference-OPENSSL_ia32cap_P-at-Intel-machine-code-le.patch \
           file://0249-AES-GCM-enabled-with-AVX512-vAES-and-vPCLMULQDQ.-692.patch \
           file://0250-Update-pbkdf2-service-indicator-to-require-lower-bou.patch \
           file://0251-TLS-1.3-Transfer-Support-891.patch \
           file://0252-Bump-AWS-LC-API-version-900.patch \
           file://0253-Factor-out-C-level-implementation-of-curve25519-arit.patch \
           file://0254-Don-t-use-negative-values-for-unimplemented-modes.patch \
           file://0255-Move-Go-CMake-support-into-its-own-file.patch \
           file://0256-VMS-I-don-t-think-so.-Take-this-for-a-walk-behind-th.patch \
           file://0257-Bound-the-overall-output-size-of-ASN1_generate_v3.patch \
           file://0258-Add-a-note-in-INCORPORATING-about-which-branch-to-us.patch \
           file://0259-Add-OPENSSL_asprintf-and-friends-for-asprintf-3-func.patch \
           file://0260-Make-ERR-and-thread-use-system-malloc.patch \
           file://0261-Cap-decimal-input-sizes-in-s2i_ASN1_INTEGER.patch \
           file://0262-Make-OPENSSL_malloc-push-ERR_R_MALLOC_FAILURE-on-fai.patch \
           file://0263-Remove-remaining-ERR_R_MALLOC_FAILURE-calls-in-code-.patch \
           file://0264-Fix-a-Wignored-qualifiers-warning-in-trust_token_tes.patch \
           file://0265-Align-the-hash-to-curve-formulation-with-draft-16.patch \
           file://0266-Implement-P256_XMD-SHA-256_SSWU_RO_-and-P384_XMD-SHA.patch \
           file://0267-Unify-the-two-copies-of-bn_add_words-and-bn_sub_word.patch \
           file://0268-Ignore-cmake-files-in-the-licensce-check.patch \
           file://0269-Actually-disable-Go-in-the-ancient-CI.-This-previous.patch \
           file://0270-TLS-1.3-Transfer-Fuzzing-929.patch \
           file://0271-Release-v1.7.0-933.patch \
           file://0272-Update-size-of-BORINGSSL_function_hit-to-account-for.patch \
           file://0273-Add-missing-boringssl_prefix_symbols-target-931.patch \
           file://0274-Add-back-ASN1_STRING_clear_free-that-was-accidentall.patch \
           file://0275-Re-factor-machine-level-optimisation-decision-logic-.patch \
           file://0276-Improved-support-for-OpenSSH-894.patch \
           file://0277-Release-v1.8.0-944.patch \
           file://0278-Delete-leftover-code-from-previous-Kyber-implementat.patch \
           file://0279-Remove-Gitter-from-README.md-947.patch \
           file://0280-Per-file-namespace-for-symbolic-labels.patch \
           file://0281-Per-file-namespace-for-symbolic-labels.patch \
           file://0282-Provide-a-compile-option-to-disable-AVX512-specific-.patch \
           file://0283-AES-GCM-optimised-for-AArch64-with-EOR3-instruction-.patch \
           file://0284-Let-service-indicator-check-for-tls1.0-1.1-context-9.patch \
           file://0285-Add-Jitter-speed-test-for-FIPS-build-951.patch \
           file://0286-Remove-proxy-certificate-support.patch \
           file://0287-Tidy-up-check_chain_extensions-after-proxy-certifica.patch \
           file://0288-Update-build-tools.patch \
           file://0289-Make-EVP_PKEY-opaque.patch \
           file://0290-Revert-go-build-ignore-lines.patch \
           file://0291-Move-constants-from-.text-to-.rodata-on-aarch64.patch \
           file://0292-Update-build-files-in-generated-src.patch \
           file://0293-Support-older-versions-of-AWS-LC-that-still-need-SHA.patch \
           file://0294-Make-the-AES-GCM-avx512-Perl-script-compatible-with-.patch \
           file://0295-Zeroize-shared_point-in-ECDH-956.patch \
           file://0296-Ensure-XTS-mode-API-allows-only-re-initialising-the-.patch \
           file://0297-Update-CI-to-AL2023-961.patch \
           file://0298-Don-t-use-a-pre-calculated-digest-for-signing-and-ve.patch \
           file://0299-Use-EVP_DigestSign-Verify-for-RSA-PWCT-957.patch \
           file://0300-Wire-up-s2n-bignum-x25519-backend-939.patch \
           file://0301-Clarify-EC_POINT_point2bn-docs-966.patch \
           file://0302-add-test-for-libssl-off-959.patch \
           file://0303-aesv8-armx.pl-Avoid-buffer-overread-in-AES-XTS-decry.patch \
           file://0304-Release-v1.9.0-972.patch \
           file://0305-Update-Go-dependencies.patch \
           file://0306-acvp-write-updated-tests-without-.bz2-suffix.patch \
           file://0307-Fix-Android-tests-with-new-recipe-changes.patch \
           file://0308-Gracefully-handle-DSA-objects-with-missing-fields.patch \
           file://0309-Reject-zero-ECDSA-keys-in-EC_KEY_set_private_key.patch \
           file://0310-Add-more-DSA-consistency-checks.patch \
           file://0311-Cap-the-number-of-ECDSA-and-DSA-sign-iterations.patch \
           file://0312-Tweak-urandom_test-for-Android-devices-without-getra.patch \
           file://0313-Move-data-from-.text-to-.rodata-on-x86_64.patch \
           file://0314-Print-the-reason-the-child-stopped-in-urandom_test.patch \
           file://0315-Require-getauxval-on-32-bit-Arm-Linux.patch \
           file://0316-Create-the-SSLKeyShare-object-in-TLS-1.2-client-ECDH.patch \
           file://0317-Move-the-ASN.1-based-SSLKeyShare-serialization-to-ha.patch \
           file://0318-Simplify-ECKeyShare-slightly.patch \
           file://0319-Generate-build-files.patch \
           file://0320-Remove-cruft-from-generate-build-script-976.patch \
           file://0321-Retire-Armv7-x25519-implementation-973.patch \
           file://0322-P-384-521-runtime-check-for-s2n-bignum-on-aarch64-98.patch \
           file://0323-Update-EVP-AES-GCM-and-XTS-benchmarks-to-reuse-the-k.patch \
           file://0324-test-case-when-xts-mode-key-and-tweak-init-is-done-s.patch \
           file://0325-aws-lc-rs-workflow-971.patch \
           file://0326-Add-DH_check-support-to-perf-tool-982.patch \
           file://0327-Add-missing-symbols-for-postgres-979.patch \
           file://0328-Switch-to-CIPD-s-copy-of-perl.patch \
           file://0329-Pick-up-a-VS-2022-toolchain-from-Chromium.patch \
           file://0330-Run-Go-tests-as-part-of-run_tests.patch \
           file://0331-Workaround-yet-more-NULL-0-language-bugs.patch \
           file://0332-Fix-up-go-test-to-cater-for-dimensions-that-doesn-t-.patch \
           file://0333-add-benchmarks-for-EC_KEY_generate_key-_fips-969.patch \
           file://0334-fix-device-farm-CI-build-with-boto3-990.patch \
           file://0335-Fix-various-minor-memory-leaks-in-speed.cc-988.patch \
           file://0336-Enable-valgrind-tests-on-AArch64.-978.patch \
           file://0337-Fix-two-trailing-new-lines-998.patch \
           file://0338-Provide-OPENSSL_cpuid_setup-for-OpenBSD-aarch64.-962.patch \
           file://0339-Add-postgres-integration-test-ci-986.patch \
           file://0340-P-384-521-fallback-to-small-implementation-when-OPEN.patch \
           file://0341-Fix-ninja-run_tests.patch \
           file://0342-Use-the-common-location-for-CMake-in-the-bots.patch \
           file://0343-Fix-use-of-unitialized-cbb-on-failure-case.patch \
           file://0344-Add-a-few-more-assertions-to-compiler_test.cc.patch \
           file://0345-Plug-a-leak-in-ASN1_item_i2d.patch \
           file://0346-Work-around-a-NASM-bug.patch \
           file://0347-test_fips-flush-stdout-before-aborting-on-failure.patch \
           file://0348-Add-prefetch-to-sha1_block_data_order_shaext.patch \
           file://0349-Add-OPENSSL_EXPORT-to-BN_mod_inverse_blinded.patch \
           file://0350-Test-that-X509_NAMEs-sort-their-RDNs-when-encoding.patch \
           file://0351-Const-correct-and-document-a-few-functions-in-x509v3.patch \
           file://0352-Add-CTRDBG_STATE-to-bssl-UniquePtr.patch \
           file://0353-Add-a-test-for-OPTIONAL-CHOICE-values.patch \
           file://0354-Update-build-files-in-generated-src.patch \
           file://0355-Remove-EVP_PKEY_ASN1_METHOD-and-EVP_PKEY_METHOD-from.patch \
           file://0356-AWS-CodeBuild-GitHub-Job-Pruner-980.patch \
           file://0357-add-fixes-pointed-out-by-static-analysis-995.patch \
           file://0358-Add-Openssh-integration-tests-to-CI-942.patch \
           file://0359-add-support-for-X509_get0_pubkey-1000.patch \
           file://0360-Fix-incorrect-lambda-CodeBuild-policy-permission-100.patch \
           file://0361-Check-HWCAP_CPUID-before-reading-MIDR_EL1-on-aarch64.patch \
           file://0362-Only-build-acvp-modulewrapper-with-BUILD_TESTING-101.patch \
           file://0363-Run-FIPS-break-tests-as-a-part-of-the-CI-1005.patch \
           file://0364-Fix-for-building-on-aarch64-with-32-bit-OS-1015.patch \
           file://0365-Merge-integrate-pq-into-main-897.patch \
           file://0366-Reduce-type-punning-in-ASN1_TYPE.patch \
           file://0367-Rewrite-ASN1_OBJECT-and-ASN1_BOOLEAN-d2i-i2d-functio.patch \
           file://0368-Make-ASN1_OBJECT_create-size_t-clean.patch \
           file://0369-Rewrite-c2i_ASN1_OBJECT.patch \
           file://0370-Fix-parameter-name-for-i2d_X509_EXTENSION.patch \
           file://0371-Add-a-warning-about-OBJ_create-and-global-state.patch \
           file://0372-Fix-typo-s-and-clarify-some-language-993.patch \
           file://0373-Bump-AWSLC_VERSION_NUMBER_STRING-to-1.10.0-1019.patch \
           file://0374-Revert-Temporarily-remove-dilithium-KATs-and-fuzz-co.patch \
           file://0375-Add-additional-no-op-symbols-for-support-mySQL-1002.patch \
           file://0376-Update-speed.cc-to-support-older-versions-of-AWS-LC-.patch \
           file://0377-Reduce-the-ARM-fuzz-time-to-get-the-CI-to-pass-in-un.patch \
           file://0378-Add-support-for-SSL_-read-peek-write-_ex-1010.patch \
           file://0379-Delete-leftover-comments-about-KEMs-Kyber-1013.patch \
           file://0380-Add-AES-CTR-benchmark-1024.patch \
           file://0381-Sort-various-X.509-global-lists-sooner.patch \
           file://0382-Const-correct-sk_FOO_cmp_func.patch \
           file://0383-Remove-dynamic-X509_VERIFY_PARAM-registration.patch \
           file://0384-Add-comment-about-regenerating-peg-files.patch \
           file://0385-Add-various-tests-for-memory-BIOs.patch \
           file://0386-Convert-a-few-more-ints-to-bools-in-libssl.patch \
           file://0387-Remove-delocate-README.md-as-delocate.peg-includes-b.patch \
           file://0388-add-support-for-SSL_get_key_update_type-and-SSL_KEY_.patch \
           file://0389-Add-support-for-EVP_aes_256_wrap-1007.patch \
           file://0390-Fix-RSA-and-ECDSA-SigGen-w-SHA2-512-256-1020.patch \
           file://0391-Add-LDTs-to-ACVP-Tool-1029.patch \
           file://0392-Add-support-for-multiple-filters-for-bssl-speed-appl.patch \
           file://0393-quiet-unused-arguments-on-Android-to-silence-noexecs.patch \
           file://0394-Add-few-compatability-functions-needed-for-HAProxy-1.patch \
           file://0395-Expose-TLS-prf-1033.patch \
           file://0396-Add-ASN1_TIME_to_tm-1035.patch \
           file://0397-Zeroize-unused-Dilithium-key-buffers-1031.patch \
           file://0398-Add-function-for-KEM-key-check-1030.patch \
           file://0399-Add-additional-DH-groups-from-RFC-7919-1039.patch \
           file://0400-Document-X509_NAME_oneline-function-behavior.-1040.patch \
           file://0401-set-rsa-pkcs1v1.5-and-ecdsa-sig-ver-with-SHA512-256-.patch \
           file://0402-Add-Support-for-RSA-SigGen-w-SHA2-512-256-PKCS1v1.5-.patch \
           file://0403-Ensure-CodeBuild-always-has-GOPROXY-set-via-buildspe.patch \
           file://0404-Split-up-integration-test-ci-dimension-1036.patch \
           file://0405-AES-XTS-optimization-using-vAES-and-vPCLMULQDQ-1004.patch \
           file://0406-Simplify-speed.cc-if-defs-for-different-libcryptos-1.patch \
           file://0407-Fix-size_t-truncations-in-bio_mem.c.patch \
           file://0408-Tidy-up-some-lengths-in-SSL_SESSION.patch \
           file://0409-RESOURCE_LEAK-in-method-STACK_OF-TRUST_TOKEN-voprf_u.patch \
           file://0410-Don-t-consume-the-newline-in-BIO_gets-for-fds.patch \
           file://0411-If-the-ret-is-not-null-it-needs-to-be-released-befor.patch \
           file://0412-Remove-SSL_CIPHER_get_rfc_name.patch \
           file://0413-Fix-miscellaneous-size_t-truncations.patch \
           file://0414-Add-Trust-Token-version-using-standardized-hash2curv.patch \
           file://0415-Fix-up-do_ext_i2d-s-error-handling.patch \
           file://0416-Add-functions-to-allow-the-mocking-of-AES-hw-support.patch \
           file://0417-Remove-support-for-old-style-X509V3_EXT_METHODs.patch \
           file://0418-Remove-X509V3_EXT_add_list-and-X509V3_EXT_cleanup.patch \
           file://0419-Skip-some-BIO_gets-tests-if-tmpfile-fails-on-Android.patch \
           file://0420-Fix-aesni-xts-avx512-to-support-Perl-v5.8.8-1053.patch \
           file://0421-Merge-OCSP-request-feature-branch-to-main-1054.patch \
           file://0422-Change-the-Jitter-entropy-recovery-mechanism-1058.patch \
           file://0423-add-Wmissing-braces-to-build-1061.patch \
           file://0424-Allow-cleanup-of-thread-local-data-before-dlclose-10.patch \
           file://0425-break-tests.sh-break-run-time-tests-and-use-two-test.patch \
           file://0426-Widen-ASN1_mbstring_copy-and-ASN1_mbstring_ncopy-to-.patch \
           file://0427-Document-a-pile-of-X509-print-functions.patch \
           file://0428-Organize-X509_ATTRIBUTE-functions-into-sections.patch \
           file://0429-Move-the-X509-time-functions-under-Convenience-funct.patch \
           file://0430-Clarify-in-ssl.h-documentation-not-to-use-the-verify.patch \
           file://0431-Update-docs-to-recommend-a-much-more-convenient-CMak.patch \
           file://0432-Replace-sort.Sort-with-sort.Slice.patch \
           file://0433-Remove-the-X509at_-functions.patch \
           file://0434-Drop-CECPQ2-support.patch \
           file://0435-Trim-some-unused-XN_FLAG_-values.patch \
           file://0436-Bump-AWSLC_VERSION_NUMBER_STRING-to-1.11.0-1056.patch \
           file://0437-Update-CI-README-as-a-follow-up-to-PR-978-1066.patch \
           file://0438-Additional-tests-for-failure-modes-for-KEM-API-1048.patch \
           file://0439-Fix-potential-NULL-pointer-dereference-1067.patch \
           file://0440-add-integration-build-CI-dimension-for-mySQL-1051.patch \
           file://0441-add-integration-test-CI-dimension-for-MariaDB-1046.patch \
           file://0442-Add-SSL_get0_verified_chain-1055.patch \
           file://0443-Add-OSSL_HANDSHAKE_STATE-enum-for-OpenSSL-compatabil.patch \
           file://0444-Allow-passing-extra-flags-to-BoGo-shim.patch \
           file://0445-Move-convert_wycheproof-into-its-own-package.patch \
           file://0446-Re-add-go-build-ignore-lines.patch \
           file://0447-Align-TRUST_TOKEN_pst_v1_voprf-with-draft-21-of-VOPR.patch \
           file://0448-Add-some-missing-includes.patch \
           file://0449-X509_sign-etc.-should-return-the-length-of-the-signa.patch \
           file://0450-Remove-go-build-ignore-from-convert_wycheproof.patch \
           file://0451-Remove-unimplemented-SSL-BIO_ctrl-values.patch \
           file://0452-Fix-DISABLE_PERL-on-builds-for-non-asm-platforms-106.patch \
           file://0453-Fix-BORINGSSL_PREFIX-build-for-ppc64le-1069.patch \
           file://0454-align-X509_VERIFY_PARAM-host-and-email-behavior-with.patch \
           file://0455-Use-build-in-string-copy-function-1078.patch \
           file://0456-Light-tidy-up-of-required-dependency-versions-1076.patch \
           file://0457-Remove-unused-variable-declaration-in-ssl_test.cc-10.patch \
           file://0458-Move-the-old-SPKAC-types-to-their-own-section.patch \
           file://0459-runner-Remove-an-unnecessary-use-of-AllCurves.patch \
           file://0460-Invalidated-cached-RSA-DH-and-DSA-state-when-changin.patch \
           file://0461-Disable-BlindingCacheConcurrency-on-FreeBSD.patch \
           file://0462-Replace-interface-with-any.patch \
           file://0463-Update-references-to-draft-irtf-cfrg-gcmsiv.patch \
           file://0464-Implement-the-AuthEncap-AuthDecap-HPKE-modes.patch \
           file://0465-Bump-GO-version-of-module.patch \
           file://0466-Update-build-files-in-generated-src.patch \
           file://0467-Reapply-Remove-support-for-old-style-X509V3_EXT_METH.patch \
           file://0468-Make-PRNG-model-slightly-more-readable-1079.patch \
           file://0469-Add-back-custom-extension-support-for-libssl-1071.patch \
           file://0470-Save-leaf-certificate-in-SSL-early-to-avoid-losing-e.patch \
           file://0471-Mark-include-as-PUBLIC-not-SYSTEM-PUBLIC-1081.patch \
           file://0472-Release-v1.12.0-1085.patch \
           file://0473-Disable-two-Visual-Studio-17-2022-warnings-1087.patch \
           file://0474-Add-HAProxy-to-our-CI-1083.patch \
           file://0475-Align-OCSP-behavior-with-OpenSSL-for-nginx-1077.patch \
           file://0476-Merge-and-remove-duplicate-yml-files-in-CI-1088.patch \
           file://0477-Export-additional-OCSP-functions-already-in-the-publ.patch \
           file://0478-Add-a-shared-library-build-with-HAProxy-to-the-CI-10.patch \
           file://0479-Allow-SHA3-digests-with-EC-key-types-1094.patch \
           file://0480-Release-v1.12.1-1095.patch \
           file://0481-EVP-API-ECDHE-speed-tool-support-1080.patch \
           file://0482-fix-rust-sanity-check-CI-1106.patch \
           file://0483-Silence-static-analyser-by-validating-pointer-prior-.patch \
           file://0484-Improve-LICENSE-readability-1110.patch \
           file://0485-add-back-CERT_PKEY-structure-and-refactor-pointers-1.patch \
           file://0486-Turn-on-tests-in-CI-dimension-for-mySQL-1063.patch \
           file://0487-Fix-DH_check-excessive-time-with-oversized-modulus-1.patch \
           file://0488-Add-GitHub-CODEOWNERS-1103.patch \
           file://0489-Avoid-using-assembler-macros-and-rename-labels-in-th.patch \
           file://0490-Add-BoringSSL-Dispatch-Test-for-aarch64-1093.patch \
           file://0491-Run-additional-HAProxy-tests-1097.patch \
           file://0492-Add-webhook-event-support-for-push-to-main-and-fips-.patch \
           file://0493-Remove-CRNGT-1112.patch \
           file://0494-Add-NEON-versions-of-functions-for-RSA-2048-and-4096.patch \
           file://0495-Make-dispatch-tests-use-corruptible-registers-on-aar.patch \
           file://0496-Allow-SSL_CTX-to-use-the-new-multiple-certificate-sl.patch \
           file://0497-Don-t-make-assumptions-about-GCM128_CONTEXT-layout-i.patch \
           file://0498-Don-t-make-assumptions-about-GCM128_CONTEXT-layout-i.patch \
           file://0499-Remove-H-from-GCM128_KEY.patch \
           file://0500-Remove-unions-in-polyval-implementation.patch \
           file://0501-Clarify-that-X25519-also-supports-EVP_PKEY_new_raw_p.patch \
           file://0502-Rename-EC_RAW_POINT-to-EC_JACOBIAN.patch \
           file://0503-Update-build-files-in-generated-src.patch \
           file://0504-tweak-back-error-string-functions-with-exclamation-m.patch \
           file://0505-Support-changing-OPENSSL_armcap-with-environment-var.patch \
           file://0506-Abstract-fips-entropy-functions-1113.patch \
           file://0507-silence-static-analyser-with-additional-checks-1123.patch \
           file://0508-Fix-Excessive-time-spent-checking-DH-q-parameter-val.patch \
           file://0509-Release-v1.13.0-1126.patch \
           file://0510-fix-formal-verification-CI-1130.patch \
           file://0511-Fix-PKCS8Test-to-not-rely-on-RSA-512.patch \
           file://0512-Add-APIs-to-query-a-list-of-possible-strings-for-TLS.patch \
           file://0513-Remove-unions-in-BLAKE2b-implementation.patch \
           file://0514-Update-build-tools.patch \
           file://0515-Cap-the-input-size-to-the-conf-fuzzer.patch \
           file://0516-Use-a-helper-function-to-implement-get_all_foo_names.patch \
           file://0517-Remove-unions-in-GCM-implementation.patch \
           file://0518-Implementation-passive-entropy-1125.patch \
           file://0519-add-curl-integration-test-ci-dimension-1134.patch \
           file://0520-Retrieve-multiple-certificate-slot-for-TLS1.2-1.3-ba.patch \
           file://0521-ABI-Diff-GitHub-Action-1116.patch \
           file://0522-Add-vzeroupper-instruction-for-AVX512-optimization-i.patch \
           file://0523-Avoid-UB-1140.patch \
           file://0524-Simplify-the-Kyber-prefix-build-1131.patch \
           file://0525-Detect-GCM-SIV-alignment-change-1144.patch \
           file://0526-Retrieve-multiple-certificate-slot-for-TLS1.0-1.1-ba.patch \
           file://0527-Update-for-Release-v1.14.0-1150.patch \
           file://0528-Add-EVP_MD_do_all-1154.patch \
           file://0529-error-s-directive-argument-is-null-1158.patch \
           file://0530-fix-build-on-gcc4.8.3-1156.patch \
           file://0531-Remove-duplicate-handling-of-OPENSSL_NO_ASM-from-CMa.patch \
           file://0532-Add-DBUILD_TOOL-OFF-to-CMake.-1148.patch \
           file://0533-Upstream-merge-2023-08-09-1152.patch \
           file://0534-Revert-Upstream-merge-2023-08-09-1152-1160.patch \
           file://0535-Add-documentation-for-X509_STORE_CTX_set_verify_cb-a.patch \
           file://0536-Use-Windows-Interlocked-APIs-for-refcounts-when-C11-.patch \
           file://0537-Add-a-thread-test-for-ex_data.patch \
           file://0538-Fix-RAND_enable_fork_unsafe_buffering-when-called-af.patch \
           file://0539-Update-hkdf.c-to-avoid-potentially-vulnerable-code-p.patch \
           file://0540-Add-a-comment-about-the-Chromium-sandbox-for-macOS-s.patch \
           file://0541-Bound-STACK_OF-T-sizes-by-int.patch \
           file://0542-acvptool-clean-up-better.patch \
           file://0543-add-missing-symbols-for-SSLProxy-support-1155.patch \
           file://0544-Document-and-test-DH_generate_key-s-weird-key-reuse-.patch \
           file://0545-Update-montgomery-multiplication-to-use-s2n-bignum-s.patch \
           file://0546-Consistently-reject-large-p-and-large-q-in-DH.patch \
           file://0547-Default-to-q-p-1-2-for-DH-keygen.patch \
           file://0548-Add-more-ssl-runner-tests-for-multiple-certificate-s.patch \
           file://0549-Minor-fix-in-aead-test-1165.patch \
           file://0550-Conditionally-enable-Neon-version-of-s2n-bignum-impl.patch \
           file://0551-Fix-build-for-ppc64le-1167.patch \
           file://0552-add-additional-X509-documentation-1142.patch \
           file://0553-Preparing-for-release-v1.15.0-1171.patch \
           file://0554-Add-int-casts-as-needed-around-STACK_OF-T-sizes-and-.patch \
           file://0555-Miscellaneous-size_t-truncation-fixes.patch \
           file://0556-Test-the-CONF-parser-more-extensively.patch \
           file://0557-Remove-some-unnecessary-NULL-checks-in-conf.c.patch \
           file://0558-Remove-some-unreachable-character-types-in-the-CONF-.patch \
           file://0559-Remove-variable-expansion-from-CONF-fuzzer.patch \
           file://0560-Add-prefetch-to-aes_hw_ctr32_encrypt_blocks.patch \
           file://0561-Add-an-ABI-test-for-x25519_NEON.patch \
           file://0562-Remove-SSL_CIPHER_get_value.patch \
           file://0563-Align-on-using-the-group-over-curve-for-ECDH-in-TLS.patch \
           file://0564-Align-remaining-TLS-ECDH-APIs-on-group-terminology.patch \
           file://0565-Add-prefetch-to-aesni_ctr32_ghash_6x.patch \
           file://0566-Update-build-files-in-generated-src.patch \
           file://0567-Add-support-for-LoongArch.-1137.patch \
           file://0568-Lower-returned-number-for-SSL_CTX_get_security_level.patch \
           file://0569-Add-AWS-LC-version-number-to-both-OpenSSL_version-an.patch \
           file://0570-Simplify-HAProxy-integration-tests-by-using-built-in.patch \
           file://0571-Fix-and-add-CI-for-postgres-build-on-arm-1176.patch \
           file://0572-Align-with-OpenSSL-on-TLS-1.3-cipher-suite-constants.patch \
           file://0573-More-alignment-with-OpenSSL-on-TLS-1.3-cipher-suite-.patch \
           file://0574-Fix-Compiler-Error-on-GCC-13-1184.patch \
           file://0575-add-integration-CI-dimension-for-nginx-1143.patch \
           file://0576-Alias-RAND_priv_bytes-to-RAND_bytes-1180.patch \
           file://0577-Add-BN_CTX_secure_new-alias-for-BN_CTX_new.patch \
           file://0578-Simplify-Prefix-Build-Support-1178.patch \
           file://0579-Check-for-unset-certificates-in-servers-1181.patch \
           file://0580-Add-prefix-symbols-for-Windows-FIPS-Shared-Build-119.patch \
           file://0581-MSVC-2022-Ignore-C5266-and-C5267-1190.patch \
           file://0582-Fix-AVX512-capability-check-1193.patch \
           file://0583-Disable-XTS-use-of-AVX512-on-Windows-1195.patch \
           file://0584-Use-passive-entropy-source-method-by-default-for-FIP.patch \
           file://0585-Add-bignum_copy_row_from_table-and-its-Neon-variants.patch \
           file://0586-add-patch-and-integration-CI-dimension-for-sslproxy-.patch \
           file://0587-Remove-unions-in-EC_SCALAR-and-EC_FELEM.patch \
           file://0588-Remove-a-few-lingering-references-to-Rust.patch \
           file://0589-Calibrate-BN_window_bits_for_ctime_exponent_size-to-.patch \
           file://0590-Bump-release-version-to-v1.16.0-1207.patch \
           "
SRCREV = "329d23ce93d42b9017502ac24ca073ebdaa7660f"

S = "${WORKDIR}/git"

inherit cmake ptest pkgconfig

PACKAGECONFIG ??= "\
    ${@bb.utils.contains('PTEST_ENABLED', '1', 'with-tests', '', d)} \
    "

# CMAKE_CROSSCOMPILING=ON will disable building the tests
PACKAGECONFIG[with-tests] = "-DBUILD_TESTING=ON -DCMAKE_CROSSCOMPILING=OFF,-DBUILD_TESTING=OFF,"

# enable PACKAGECONFIG = "static" to build static instead of shared libs
PACKAGECONFIG[static] = "-DBUILD_SHARED_LIBS=OFF,-DBUILD_SHARED_LIBS=ON"

do_install_ptest () {
   install -d ${D}${PTEST_PATH}/tests
   cp -r ${B}/libboringssl_gtest.so ${D}${PTEST_PATH}/tests/
   install -m 0755 ${B}/ssl/ssl_test ${D}${PTEST_PATH}/tests/
}

EXTRA_OECMAKE += "\
    -DDISABLE_PERL=ON \
    -DDISABLE_GO=ON \
"

CXXFLAGS += "-Wno-ignored-attributes"

FILES:${PN} += "\
    ${libdir}/libcrypto.so \
    ${libdir}/libssl.so \
    ${libdir}/libdecrepit.so \
    "

FILES:${PN}-dev += "${libdir}/*/cmake"

# also test depend-on-us packages build
RDEPENDS:${PN}-ptest = "\
    aws-c-auth \
    aws-c-cal \
    aws-c-compression \
    aws-c-io \
    aws-c-s3 \
    aws-checksums \
    "

# Notify that libraries are not versioned
FILES_SOLIBSDEV = ""

BBCLASSEXTEND = "native nativesdk"

BRANCH = "fips-2022-11-02"
