#!/bin/sh

jobs_demo_mosquitto 
RETVAL=$?
if [ $RETVAL -eq 1 ] ; then
    echo "PASS: backoffalgorithm: aws-iot-device-sdk-embedded-c-jobs_demo_mosquitto simple-test"
else
    echo "FAIL: backoffalgorithm: aws-iot-device-sdk-embedded-c-jobs_demo_mosquitto simple-test"
fi
