#!/bin/sh

aws-iot-device-sdk-cpp-v2-samples-fleet-provisoning --help
RETVAL=$?
if [ $RETVAL -eq 0 ] ; then
    echo "PASS: aws-iot-device-sdk-cpp-v2-sample-fleet-provisioning help test"
else
    echo "FAIL: aws-iot-device-sdk-cpp-v2-sample-fleet-provisioning help test"
fi
