#!/bin/sh

jobs_demo_mosquitto 
RETVAL=$?
if [ $RETVAL -eq 0 ] ; then
    echo "PASS: aws-iot-device-sdk-embedded-c-jobs_demo_mosquitto: simple-test"
else
    echo "FAIL: aws-iot-device-sdk-embedded-c-jobs_demo_mosquitto: simple-test"
fi
