#!/bin/sh

defender_demo
RETVAL=$?
if [ $RETVAL -eq 1 ] ; then
    echo "PASS: aws-iot-device-sdk-embedded-c-defender-demo-json: simple test"
else
    echo "FAIL: aws-iot-device-sdk-embedded-c-defender-demo-json: simple test"
fi
