#!/bin/sh

 fleet_provisioning_keys_cert

RETVAL=$?
if [ $RETVAL -eq 1 ] ; then
    echo "PASS: aws-iot-device-sdk-embedded-c-fleet-provisioning-keys-cert: simple test"
else
    echo "FAIL: aws-iot-device-sdk-embedded-c-fleet-provisioning-keys-cert: simple test"
fi
