#!/bin/sh

shadow_demo_main
RETVAL=$?
if [ $RETVAL -eq 1 ] ; then
    echo "PASS: aws-iot-device-sdk-embedded-c-shadow-demo-main: simple test"
else
    echo "FAIL: aws-iot-device-sdk-embedded-c-shadow-demo-main: simple test"
fi
