#!/bin/sh

# Test dependency conflicts using shared library
python3 python_dependency_test.py s3transfer botocore multiprocessing urllib3 boto3

# Run original unit tests
TESTS="\
unit/test_bandwidth.py \
unit/test_compat.py \
unit/test_copies.py \
"

for TEST in $TESTS
do
    pytest tests/$TEST -o log_cli=true -o log_cli_level=INFO | sed -e 's/\[...%\]//g'| sed -e 's/PASSED/PASS/g'| sed -e 's/FAILED/FAIL/g'| sed -e 's/SKIPPED/SKIP/g'| awk '{if ($NF=="PASS" || $NF=="FAIL" || $NF=="SKIP" || $NF=="XFAIL" || $NF=="XPASS"){printf "%s: %s\n", $NF, $0}else{print}}'| awk '{if ($NF=="PASS" || $NF=="FAIL" || $NF=="SKIP" || $NF=="XFAIL" || $NF=="XPASS") {$NF="";print $0}else{print}}'
done
