#!/bin/sh

echo "SKIP: aws-iot-device-sdk-embedded-c-http-demo-s3-download: basic test - requires a valid AWS account and S3 bucket to run"

# http_demo_s3_download
# 
# RETVAL=$?
# if [ $RETVAL -eq 139 ] ; then
#     echo "PASS: aws-iot-device-sdk-embedded-c-http-demo-s3-download: basic test"
# else
#     echo "FAIL: aws-iot-device-sdk-embedded-c-http-demo-s3-download: basic test"
# fi
