name: Auto-merge automatic updates.
on:
  check_suite:
    types:
      - completed
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.15.3"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: "version-upgrade"
          MERGE_METHOD: "rebase"
          MERGE_FILTER_AUTHOR: "aws-iot-embedded-linux-ci"
