version: 0.2
run-as: aws-yocto-builder
env:
  git-credential-helper: yes
phases:
  pre_build:
    run-as: root
    commands:
      - mkdir -p /build-output
      - chown aws-yocto-builder:aws-yocto-builder /build-output
      - chown aws-yocto-builder:aws-yocto-builder /downloads
      - chown aws-yocto-builder:aws-yocto-builder /sstate-cache
      - chmod 777 /build-output
      - chmod 777 /downloads
      - chmod 777 /sstate-cache
      - git config --global user.name "Cloudy Builder"
      - git config --global user.email "email@example.com"
  build:
    commands:
      - curl https://storage.googleapis.com/git-repo-downloads/repo > $HOME/repo
      - chmod +x $HOME/repo
      - mkdir $HOME/dist
      - cd $HOME/dist
      - $HOME/repo init -u https://github.com/aws/meta-aws -m qa/repo.checklayer.${YP_RELEASE}.xml
      - $HOME/repo sync
      - export PATH=$HOME/dist/poky/scripts:$HOME/dist/poky/bitbake/bin:$PATH
      - export BUILDDIR=$CODEBUILD_SRC_DIR/qa/checklayer
      - export BBPATH=$CODEBUILD_SRC_DIR/qa/checklayer
      - export BB_ENV_EXTRAWHITE=ALL_PROXY BBPATH_EXTRA BB_LOGCONFIG BB_NO_NETWORK BB_NUMBER_THREADS BB_SETSCENE_ENFORCE BB_SRCREV_POLICY DISTRO FTPS_PROXY FTP_PROXY GIT_PROXY_COMMAND HTTPS_PROXY HTTP_PROXY MACHINE NO_PROXY PARALLEL_MAKE SCREENDIR SDKMACHINE SOCKS5_PASSWD SOCKS5_USER SSH_AGENT_PID SSH_AUTH_SOCK STAMPS_DIR TCLIBC TCMODE all_proxy ftp_proxy ftps_proxy http_proxy https_proxy no_proxy
      - sed -i -e "s,DIST,$HOME/dist," -e "s,CODEBUILD_SRC_DIR,${CODEBUILD_SRC_DIR}," $CODEBUILD_SRC_DIR/qa/checklayer/conf/bblayers.conf
      - |
        yocto-check-layer \
        --dependency $HOME/dist/meta-openembedded/meta-oe $HOME/dist/meta-openembedded/meta-networking $HOME/dist/meta-openembedded/meta-python \
        --output-log ycl-check.log \
        --debug \
        --no-auto \
        --no-auto-dependency \
        $CODEBUILD_SRC_DIR/
