#!/bin/sh

export LD_PRELOAD=$(find /usr/lib /lib -type f -name "libasan.so*")

bash -c './webrtc_client_test --gtest_filter=DataChannelApiTest* --gtest_output=json:result.json ; python3 ptest_result.py result.json' 
